---

tmp_inv_dir: ''

include_tags: ''
exclude_tags: ''

provision: true

params_from_vars: {}



##########################################################################################
### OpenShift Client options
# these default values are meant to be replaced runtime if other values are to be used
# - for example 'client=kubectl'

client: oc
default_oc_action: apply
oc_ignore_unknown_parameters: true

oc_action_command: >-
  | {{ client }} {{ oc_action }} \
      {{ target_namespace }} \
      -f - \
      {{ (oc_action | regex_search('delete')) | ternary(' --ignore-not-found', '') }} \
      {{ (client == 'kubectl' and not (oc_action | regex_search('delete|patch'))) | ternary(' --validate=false', '') }} \
      {{ flags }}

