---

- name: "Reset Command Line Options"
  set_fact:
    helm_set_option: ''
    helm_values_option: ''
    helm_version_option: "{{ (helm.version|d('')|trim == '') | ternary('', ' --version \"' + helm.version|d('') + '\"') }}"
    helm_namespace_option: "{{ (helm.namespace|d('')|trim == '') | ternary('', ' --namespace \"' + helm.namespace|d('') + '\"') }}"
    helm_timeout_option: "{{ (helm.timeout|d('')|trim == '') | ternary('', ' --timeout \"' + helm.timeout|d('') + '\"') }}"

- name: "Add helm repo(s) to be used (if applicable)"
  block:
    - shell: >
        helm repo add "{{ item.name }}" "{{ item.url }}"
      loop: "{{ helm.repos }}"
    - shell: >
        helm repo update
  when:
    - helm.repos is defined
    - helm.repos|length > 0

- name: "Change 'helm.set_param' fact into command line parameters (if applicable)"
  set_fact:
    helm_set_option: "{{ helm_set_option }} --set '{{ item }}'"
  loop: "{{ helm.set_param | default([]) }}"

- name: "Change 'helm.values_param' fact into command line parameters (if applicable)"
  set_fact:
    helm_values_option: "{{ helm_values_option }} --values '{{ item }}'"
  loop: "{{ helm.values_param | default([]) }}"

- name: "{{ oc_action | capitalize }} OpenShift objects based on helm template for '{{ entry.object }} : {{ content.name | default(helm.name) }}'"
  shell: >
    helm {{ helm.action|d('template') }} \
       {{ helm.name }} {{ helm.chart }} \
       {{ helm_version_option }} \
       {{ helm_namespace_option }} \
       {{ helm_timeout_option }} \
       {{ helm_set_option }} \
       {{ helm_values_option }} \
       {{ helm.flags|d('') }} \
       {{ (helm.action|d('template') == 'template') | ternary(oc_action_command, '') }}
  register: command_result
  no_log: "{{ no_log }}"
  failed_when:
    - command_result.rc != 0
    - "'AlreadyExists' not in command_result.stderr"
